spring:
  application:
    name: spring-boot-ansible

management:
  security:
    enabled: false


info:
  app:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@