spring:
  application:
    name: spring-boot-ansible

  # disable database initialisation with Spring JDBC, enabled by default
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/demo
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate

management:
  security:
    enabled: false


info:
  app:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@


flyway:
  enabled: true

